# paths to the hydra config files in the output folder
hydra_paths: ["2021-12-15/04-11-43/"]

# if you want to manually provide a different model name to be displayed in FiftyOne
model_display_names: ["test_model"]

fifty_one_dataset_name: "rick_data_test"

# str with an absolute path to a directory containing videos for prediction.
# (it's not absolute just for the toy example)
test_videos_directory: "toy_datasets/toymouseRunningData/unlabeled_videos"

# list with absolute paths to the .csv with predictions for each vid in path_to_test_videos
path_to_csv_predictions:
  [
    "toy_datasets/toymouseRunningData/unlabeled_videos/test_vid_heatmap_temporal_0.000000.csv",
  ]

# path to save the .csv file with preds for videos
saved_video_predictions_directory: "toy_datasets/toymouseRunningData/unlabeled_videos/"

# params for loading images from the video using nvidia-dali
dali_parameters:
  # how many frames to grab at once from the video
  sequence_length: 16
