# paths to the hydra config files in the output folder, OR absolute paths to such folders.
hydra_paths: ["2021-12-15/04-11-43/"]

# TODO: decide which arg stays and which doesn't (create_labeled_video)
save_vids_after_training: True

fiftyone:
  # will be the name of the dataset (Mongo DB) created by FiftyOne. for video dataset, we will append dataset_name + "_video"
  dataset_name: "rick_data_test"

  build_speed: "slow" # "slow"/"fast". "fast" drops keypoint name and confidence information for faster processing.

  # if you want to manually provide a different model name to be displayed in FiftyOne
  model_display_names: ["test_model"]

  # whether to launch the app from the script (True), or from ipython (and have finer control over the outputs)
  launch_app_from_script: False

  remote: True # for LAI, must be False
  address: 127.0.0.1 # ip to launch the app on.
  port: 5151 # port to launch the app on.

  # whether to create a "videos" or "images" dataset, since the processes are the same
  dataset_to_create: "images"

# str with an absolute path to a directory containing videos for prediction.
# (it's not absolute just for the toy example)
test_videos_directory: "toy_datasets/toymouseRunningData/unlabeled_videos"

# str with an absolute path to directory in which you want to save .csv with predictions
saved_vid_preds_dir: "toy_datasets/toymouseRunningData"

# create labeled video from each video in test_videos_directory
create_labeled_video: true

# confidence threshold for plotting a vid
confidence_thresh_for_vid: 0.5

# params for loading images from the video using nvidia-dali
# TODO: remove, we're stopping to use this argument.
dali_parameters:
  # how many frames to grab at once from the video
  sequence_length: 16

# str with absolute path to the video file you want plotted with keypoints
video_file_to_plot: "/home/jovyan/lightning-pose/toy_datasets/toymouseRunningData/unlabeled_videos/test_vid.mp4"

# a list of strings, each points to a .csv file with predictions of a given model to the same video. will be combined with video_file_to_plot to make a visualization
pred_csv_files_to_plot:
  ["/home/jovyan/test_vid_heatmap_pca_multiview_7.500.csv"]