# path to the hydra config file in the output folder, we can use it reconstruct information about loss directory
hydra_paths:
  ["2021-10-29/13-53-17/", "2021-10-29/18-01-11/", "2021-10-31/00-11-36"]

model_names: ["toy_model_2", "toy_model_3"] # if you want to manually provide a different model name to be displayed in FiftyOne

fifty_one_dataset_name: "rick_data_test"

# path to new unlabeled videos for prediction
path_to_test_videos: "/home/jovyan/lightning-pose/toy_datasets/toymouseRunningData/unlabeled_videos" #"/datastores/mouseRunningData/1/unlabeled_videos"

# path to save the .csv file with preds:
path_to_save_predictions: null # "/home/jovyan/lightning-pose/toy_datasets/toymouseRunningData/unlabeled_videos/bla.csv" # either csv or h5

# params for loading images from the video using nvidia-dali
dali_parameters:
  # how many frames to grab at once from the video
  sequence_length: 64
