#path to the hydra config file in the output folder, we can use it reconstruct information about loss directory
hydra_paths: [
  "2021-10-15/04-24-52/",
  "2021-10-15/04-28-08/",
  "2021-10-15/04-30-19/"
]
model_names: ["baseheatmap1", "semisupervisedheatmap2", "semisupervisedregression3"] #Names could be more descriptive