language: python
python:
  - "3.8"
  - "3.9"
os:
  - osx
  - linux
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest
# only build main
branches:
  only:
  - main
