general:
  num_threads: 4 # Number of threads for data loading; can be changed
  device_id: 0 # GPU device id to use, can be changed
  device: gpu # "cpu" or "gpu"
  seed: 123456

base:
  train:
    sequence_length: 16 # step = sequence_length by default. done internally

  predict:
    sequence_length: 64 # step = sequence_length by default. done internally.

context: # not supporting context_sequences_successive 
  train: # defaults: sequence_length=5, step=sequence_length
    batch_size: 6 # default, can't be changed
    random_shuffle: True

  predict: # defaults: sequence_length=5, step=1
    batch_size: 8 # default, can't be changed