# loss = projection onto the discarded eigenvectors
pca:

  # weight in front of PCA loss
  weight: 0.6

  # Computed per dataset
  discarded_eigenvectors: null

  # Computed per dataset
  kept_eigenvectors: null

  # Computed per dataset
  epsilon: null

# loss = norm of distance between successive timepoints
temporal:

  # weight in front of temporal loss
  weight: 0.7

  # for epsilon insensitive rectification (in pixels; diffs below this are not penalized)
  epsilon: null
