training:
  train_batch_size: 16
  val_batch_size: 64
  test_batch_size: 16
  train_prob: 0.8
  val_prob: 0.1
  train_frames: 1
  num_gpus: 0
  num_workers: 8
  early_stop_patience: 3
  unfreezing_epoch: 25
  dropout_rate: 0.1
  min_epochs: 40
  max_epochs: 11
  log_every_n_steps: 1
  check_val_every_n_epoch: 10
  gpu_id: 0
  unlabeled_sequence_length: 64
  rng_seed_data_pt: 42
  rng_seed_data_dali: 43
  rng_seed_model_pt: 44
  limit_train_batches: 10
  multiple_trainloader_mode: max_size_cycle
  profiler: simple
  accumulate_grad_batches: 2
losses:
  pca_multiview:
    weight: 0.6
    discarded_eigenvectors: null
    kept_eigenvectors: null
    epsilon: null
  pca_singleview:
    weight: 0.6
    min_variance_explained: 0.95
    discarded_eigenvectors: null
    kept_eigenvectors: null
    epsilon: null
  temporal:
    weight: 0.7
    epsilon: 5.0
  unimodal:
    weight: 0.6
data:
  image_orig_dims:
    height: 406
    width: 396
  image_resize_dims:
    height: 256
    width: 256
  data_dir: toy_datasets/toymouseRunningData
  video_dir: unlabeled_videos
  csv_file: CollectedData_.csv
  header_rows:
  - 0
  - 1
  downsample_factor: 2
  num_targets: 34
  mirrored_column_matches:
  - - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
model:
  losses_to_use:
  - temporal
  resnet_version: 50
  model_type: heatmap
  model_name: my_base_toy_model
eval:
  hydra_paths:
  - 2021-11-01/00-21-04/
  - 2021-11-01/00-46-34
  model_display_names:
  - toy_model_3
  - quick_model
  fifty_one_dataset_name: rick_data_test
  path_to_test_videos:
  - toy_datasets/toymouseRunningData/unlabeled_videos
  path_to_csv_predictions:
  - toy_datasets/toymouseRunningData/unlabeled_videos/test_vid_heatmap.csv
  - toy_datasets/toymouseRunningData/unlabeled_videos/test_vid_heatmap_temporal.csv
  path_to_save_predictions: null
  dali_parameters:
    sequence_length: 64
