# list of unsupervised losses: "pca" | "temporal", default: null. if null, assume a model is supervised.
losses_to_use: ["temporal"]

# resnet version for backbone: 18 | 34 | 50 | 101 | 152
resnet_version: 50

# prediction mode: "heatmap" | "regression"
model_type: "heatmap"

# directory name for model saving
model_name: "my_base_toy_model"
