# list of unsupervised losses: "pca" | "temporal", default: null
losses_to_use: ["temporal"]

# resnet version for backbone: 18 | 34 | 50 | 101 | 152
resnet_version: 18

# whether to include a sequence of unlabeled frames; must be accompanied by non-empty losses_to_use
semi_supervised: False

# prediction mode: "heatmap" | "regression"
model_type: "heatmap"

# directory name for model saving
model_name: "my_base_toy_model"
