# list of unsupervised losses:
# - "pca_singleview"
# - "pca_multiview"
# - "temporal"
# - "unimodal_mse"
# - "unimodal_wasserstein"
# - null: if null, assume a model is supervised.
losses_to_use: ["pca_singleview"]

# whether to learn the weights for the unsupervised losses
learn_weights: False

# reach parameter for wasserstein loss
reach: None

# resnet version for backbone: 18 | 34 | 50 | 101 | 152
resnet_version: 50

# prediction mode: "heatmap" | "regression" | "heatmap_context"
model_type: "heatmap"

# which heatmap loss to use: "mse" | "wasserstein"
heatmap_loss_type: "mse"

# directory name for model saving
model_name: "context_5X1_rand"
# model_name: "baseline"

# do context (5 frames)
do_context: True
# do_context: False
