# list of unsupervised losses:
# - "pca_singleview"
# - "pca_multiview"
# - "temporal"
# - "unimodal_mse"
# - "unimodal_kl"
# - null: if null, assume a model is supervised.
losses_to_use: ["pca_singleview"]

# whether to learn the weights for the unsupervised losses
learn_weights: False

# resnet version for backbone:
# resnet18 | resnet34 | resnet50 | resnet101 | resnet152 | resnet50_contrastive
# resnet50_3d
# effb0 | effb1 | effb2
backbone: resnet50_contrastive

# prediction mode: "heatmap" | "regression" | "heatmap_context"
model_type: "heatmap"

# which heatmap loss to use: "mse" | "kl" | "js"
heatmap_loss_type: "mse"

# directory name for model saving
model_name: "my_base_toy_model"

# do context (5 frames)
do_context: False
